export * from "./Log";
import { Log } from "./Log";
export * from "./AckOffline";
import { AckOffline } from "./AckOffline";
export * from "./AckCache";
export * from "./AckQue";
export * from "./ErrorLog";
export * from "./AckApi";
import { AckApi } from "./AckApi";
export * from "./UrlVars";
import { UrlVars } from "./UrlVars";
export * from "./WindowService";
import { WindowService } from "./WindowService";
export declare const providers: (typeof AckOffline | typeof AckApi | typeof Log | typeof WindowService | typeof UrlVars)[];
