export const string = "<h3>Common Components</h3><div class=\"pad-h\"><p class=\"margin-bottom-0\">Import Example</p><pre class=\"code-sample\">import &#123; declarations as ackDecs &#125; from \"ack-angular/components\""+
"\nimport &#123; NgModule &#125; from '@angular/core';"+
"\n"+
"\n@NgModule(&#123;"+
"\n  declarations:ackDecs"+
"\n&#125;)"+
"\n</pre></div><div class=\"flex-wrap child-margin-xxs\"><div class=\"flex-1\"><div class=\"border border-grey-4x border border-bottom-0\"><div [(screenScrollModelY)]=\"screenScrollModelY\"></div><div class=\"pad-h\"><h3>screenScrollModelY</h3><p class=\"margin-0 text-grey-2x max-width-400\">Get the browser window inner width. Currently : {{screenScrollModelY}}px</p><br/></div></div><div class=\"text-center\"><div class=\"border pad-xs\" (click)=\"siewScreenScrollModelY=!siewScreenScrollModelY\" [ngClass]=\"siewScreenScrollModelY?'border-energized bg-energized':'border-info bg-info'\">view details</div></div><div class=\"border border-top-0 border-grey-4x bg-stable\" *ngIf=\"siewScreenScrollModelY\" [@500]=\"'fadeInUp'\"><h4 class=\"pad-sm margin-0\">Usage Example</h4><textarea class=\"width-full code-sample margin-0\" rows=\"3\" wrap=\"off\" ngNonBindable=\"ngNonBindable\">&lt;div(\"[(screenScrollModelY)]\"=\"screenScrollModelY\")&gt;"+
"\n  |screenScrollModelY : {{ screenScrollModelY }}px"+
"\n&lt;/div&gt;"+
"\n</textarea></div></div><div class=\"flex-1\"><div class=\"border border-grey-4x border border-bottom-0\"><div [(screenWidthModel)]=\"screenWidthModel\"></div><div class=\"pad-h\"><h3>screenWidthModel</h3><p class=\"margin-0 text-grey-2x max-width-400\">Get the browser window inner width. Currently : {{screenWidthModel}}px</p><br/></div></div><div class=\"text-center\"><div class=\"border pad-xs\" (click)=\"viewScreenWidthModel=!viewScreenWidthModel\" [ngClass]=\"viewScreenWidthModel?'border-energized bg-energized':'border-info bg-info'\">view details</div></div><div class=\"border border-top-0 border-grey-4x bg-stable\" *ngIf=\"viewScreenWidthModel\" [@500]=\"'fadeInUp'\"><h4 class=\"pad-sm margin-0\">Usage Example</h4><textarea class=\"width-full code-sample margin-0\" rows=\"3\" wrap=\"off\" ngNonBindable=\"ngNonBindable\">&lt;div(\"[(screenWidthModel)]\"=\"screenWidthModel\")&gt;"+
"\n  |screenWidthModel : {{ screenWidthModel }}px"+
"\n&lt;/div&gt;"+
"\n</textarea></div></div><div class=\"flex-1\"><div class=\"border border-grey-4x border border-bottom-0\"><div [(screenHeightModel)]=\"screenHeightModel\"></div><div class=\"pad-h\"><h3>screenHeightModel</h3><p class=\"margin-0 text-grey-2x max-width-400\">Get the browser window inner height. Currently : {{screenHeightModel}}px</p><br/></div></div><div class=\"text-center\"><div class=\"border pad-xs\" (click)=\"viewScreenHeightModel=!viewScreenHeightModel\" [ngClass]=\"viewScreenHeightModel?'border-energized bg-energized':'border-info bg-info'\">view details</div></div><div class=\"border border-top-0 border-grey-4x bg-stable\" *ngIf=\"viewScreenHeightModel\" [@500]=\"'fadeInUp'\"><h4 class=\"pad-sm margin-0\">Usage Example</h4><textarea class=\"width-full code-sample margin-0\" rows=\"3\" wrap=\"off\" ngNonBindable=\"ngNonBindable\">&lt;div(\"[(screenHeightModel)]\"=\"screenHeightModel\")&gt;"+
"\n  |screenHeightModel : {{ screenHeightModel }}px"+
"\n&lt;/div&gt;"+
"\n</textarea></div></div><div class=\"flex-1\"><div class=\"border border-grey-4x border border-bottom-0\"><div class=\"pad-h\"><h3>formChanged</h3><p class=\"margin-0 text-grey-2x max-width-400\">Capture a form tag onchange event</p><br/></div></div><div class=\"text-center\"><div class=\"border pad-xs\" (click)=\"viewFormChanged=!viewFormChanged\" [ngClass]=\"viewFormChanged?'border-energized bg-energized':'border-info bg-info'\">view details</div></div><div class=\"border border-top-0 border-grey-4x bg-stable\" *ngIf=\"viewFormChanged\" [@500]=\"'fadeInUp'\"><h4 class=\"pad-sm margin-0\">Example</h4><form class=\"pad\" (formChanged)=\"formChanges=formChanges==null?1:formChanges+1\"><span>Change Count : {{formChanges || 0}} :</span>&nbsp;<input type=\"radio\" name=\"fcTest\"/>&nbsp;<input type=\"radio\" name=\"fcTest\"/>&nbsp;<input type=\"radio\" name=\"fcTest\"/></form><h4 class=\"pad-sm margin-0\">Usage Example</h4><textarea class=\"width-full code-sample margin-0\" rows=\"9\" wrap=\"off\" ngNonBindable=\"ngNonBindable\">&lt;form (formChanged)=\"formChanges=formChanges==null?1:formChanges+1\" &gt;"+
"\n  &lt;span&gt; Change Count : {{formChanges || 0}} &lt;/span&gt;"+
"\n  &lt;input type=\"radio\" name=\"fcTest\" /&gt;"+
"\n  &lt;input type=\"radio\" name=\"fcTest\" /&gt;"+
"\n  &lt;input type=\"radio\" name=\"fcTest\" /&gt;"+
"\n&lt;/form&gt;"+
"\n</textarea></div></div><div class=\"flex-1\"><div class=\"border border-grey-4x border border-bottom-0\"><div class=\"pad-h\"><h3>shakeOn</h3><p class=\"margin-0 text-grey-2x max-width-400\">Control an animated shaking effect on demand</p><br/></div></div><div class=\"text-center\"><div class=\"border pad-xs\" (click)=\"viewShakeOn=!viewShakeOn\" [ngClass]=\"viewShakeOn?'border-energized bg-energized':'border-info bg-info'\">view details</div></div><div class=\"border border-top-0 border-grey-4x bg-stable\" *ngIf=\"viewShakeOn\" [@500]=\"'fadeInUp'\"><div class=\"pad\"><div class=\"pad-xs bg-warning border-warning text-warning\">You will need to &lt;link&gt; one of two style sheets:<ul><li>ack-angular/ack-angular.css</li><li>- or -</li><li>ack-angular/csshake.css</li></ul></div></div><h4 class=\"pad-sm margin-0\">Example</h4><div class=\"pad\"><label [shakeOn]=\"shakeOn\" (shakeThen)=\"shakeOn=false\" [(shakeRef)]=\"shakeRef\" [(shakeForMs)]=\"shakeForMs\" [(shakeType)]=\"shakeOnType\">shake this text :: {{ shakeOn||false }}</label>&nbsp;<button (click)=\"shakeOn=true\">shake:{{shakeOn||false}}</button>&nbsp;<select [(ngModel)]=\"shakeOnType\" (change)=\"shakeOn=true\"><option *ngFor=\"let item of shakeRef.shakeTypes\" value=\"{{item}}\">{{item}}</option></select>&nbsp;<input [(ngModel)]=\"shakeForMs\" (change)=\"shakeOn=true\"/></div><h4 class=\"pad-sm margin-0\">Usage Example</h4><textarea class=\"width-full code-sample margin-0\" rows=\"8\" wrap=\"off\" ngNonBindable=\"ngNonBindable\">&lt;label [shakeOn]=\"shakeOn\" (shakeThen)=\"shakeOn=false\" [(shakeRef)]=\"shakeRef\" [(shakeForMs)]=\"shakeForMs\" [(shakeType)]=\"shakeOnType\"&gt;"+
"\n  |shake this text :: {{ shakeOn||false }}"+
"\n&lt;/label&gt;"+
"\n&lt;button (click)=\"shakeOn=true\"&gt; shake:{{shakeOn||false}} &lt;/button&gt;"+
"\n&lt;select [(ngModel)]=\"shakeOnType\" (change)=\"shakeOn=true\"&gt;"+
"\n  &lt;option *ngFor=\"let item of (shakeRef?shakeRef.shakeTypes:[])\" value=\"{{item}}\"&gt;{{item}}&lt;/option&gt;"+
"\n&lt;/select&gt;"+
"\n&lt;input [(ngModel)]=\"shakeForMs\" (change)=\"shakeOn=true\" /&gt;"+
"\n</textarea></div></div></div><br/><h3>Complex Components</h3><div class=\"pad-h\"><p class=\"margin-bottom-0\">Components that have additional dependencies or restrictions</p></div><div class=\"flex-wrap child-margin-xxs\"><div class=\"flex-1 border border-grey-4x border\"><div class=\"pad-h\"><h3>route-reporter</h3><p class=\"margin-0 text-grey-2x max-width-400\">Get in tune with your document route states using @angular/router</p><br/></div><div class=\"text-center\"><div class=\"border pad-xxs\" (click)=\"viewRouteReporter=!viewRouteReporter\" [ngClass]=\"viewRouteReporter?'border-energized bg-energized':'border-info bg-info'\">view details</div></div><div class=\"border border-top-0 border-grey-4x bg-stable\" *ngIf=\"viewRouteReporter\" [@500]=\"'fadeInUp'\"><div class=\"pad\">Requirements<ul><li>route-reporter</li></ul></div><h4 class=\"pad-sm margin-0\">Usage Example</h4><textarea class=\"width-full code-sample margin-0\" rows=\"1\" wrap=\"off\" ngNonBindable=\"ngNonBindable\">&lt;route-reporter [(ref)]=\"\" (beforeChange)=\"\" (onChange)=\"\"&gt;</textarea><h4 class=\"pad-sm margin-0\">ref example</h4><textarea class=\"width-full code-sample margin-0\" rows=\"2\" wrap=\"off\" ngNonBindable=\"ngNonBindable\">&lt;route-reporter [(ref)]=\"routeState\" &gt;"+
"\n-----------------------------------------"+
"\nrouteState:{{ routeState|json }}</textarea></div></div><div class=\"flex-1 border border-grey-4x border\"><div class=\"pad-h\"><h3>ui-route-reporter</h3><p class=\"margin-0 text-grey-2x max-width-400\">Get in tune with your document route states using ui-router-ng2</p><br/></div><div class=\"text-center\"><div class=\"border pad-xxs\" (click)=\"viewUiRouteReporter=!viewUiRouteReporter\" [ngClass]=\"viewUiRouteReporter?'border-energized bg-energized':'border-info bg-info'\">view details</div></div><div class=\"border border-top-0 border-grey-4x bg-stable\" *ngIf=\"viewUiRouteReporter\" [@500]=\"'fadeInUp'\"><div class=\"pad\">Requirements<ul><li>ui-router-ng2</li></ul></div><h4 class=\"pad-sm margin-0\">Usage Example</h4><textarea class=\"width-full code-sample margin-0\" rows=\"1\" wrap=\"off\" ngNonBindable=\"ngNonBindable\">&lt;ui-route-reporter [(ref)]=\"\" (beforeChange)=\"\" (onChange)=\"\"&gt;</textarea><h4 class=\"pad-sm margin-0\">ref example</h4><textarea class=\"width-full code-sample margin-0\" rows=\"2\" wrap=\"off\" ngNonBindable=\"ngNonBindable\">&lt;ui-route-reporter [(ref)]=\"routeState\" &gt;"+
"\n-----------------------------------------"+
"\nrouteState:{{ routeState|json }}</textarea></div></div></div>"