import { AckSections } from "./components/AckSections.component";
import { AckSectionTemplates } from "./components/AckSectionTemplates.component";
import { AckModal } from "./components/AckModal.component";
import { AckModalLayout } from "./components/AckModalLayout.component";
import { AckFixedElementStage } from "./components/AckFixedElementStage.component";
import { AckFixedElement } from "./components/AckFixedElement.component";
import { AckOptions } from "./components/AckOptions.component";
import { AbsoluteOverflowX } from "./components/AbsoluteOverflowX.component";
import { ReaderHeader, ReaderBody } from "./components/ReaderHeaderBody.component";
import { AckArray } from "./directives/AckArray.directive";
import { ScrollPastFixed } from "./components/ScrollPastFixed.component";
import { ShakeOn } from "./directives/ShakeOn.directive";
import { FxOn } from "./directives/FxOn.directive";
import { FocusOn } from "./directives/FocusOn.directive";
import { ContentModel } from "./directives/ContentModel.directive";
import { SelectOn } from "./directives/SelectOn.directive";
import { InnerHtmlModel } from "./directives/InnerHtmlModel.directive";
import { ElementSizeModel } from "./directives/ElementSizeModel.directive";
import { ScreenScrollHeightDiff } from "./directives/ScreenScrollHeightDiff.directive";
import { ScreenScroll } from "./directives/ScreenScroll.directive";
import { PxFromHtmlTop } from "./directives/PxFromHtmlTop.directive";
import { ScreenScrollModelY } from "./directives/ScreenScrollModelY.directive";
import { ScreenWidthModel } from "./directives/ScreenWidthModel.directive";
import { ScreenHeightModel } from "./directives/ScreenHeightModel.directive";
import { HtmlWidthModel } from "./directives/HtmlWidthModel.directive";
import { EnterKey, EscapeKey, FormAlter, FormChanged, PreventBackKey, PreventEnterKey } from "./declarations.short";
export declare const screenDirectives: (typeof ScreenScrollModelY | typeof ScreenWidthModel | typeof ScreenHeightModel | typeof ScreenScroll | typeof ScrollPastFixed | typeof ScreenScrollHeightDiff | typeof PxFromHtmlTop)[];
export declare const declarations: (typeof SelectOn | typeof FocusOn | typeof ContentModel | typeof InnerHtmlModel | typeof EnterKey | typeof EscapeKey | typeof PreventBackKey | typeof PreventEnterKey | typeof FormChanged | typeof FormAlter | typeof ScreenWidthModel | typeof ScreenHeightModel | typeof ScrollPastFixed | typeof PxFromHtmlTop | typeof HtmlWidthModel | typeof FxOn | typeof ShakeOn | typeof ElementSizeModel | typeof AbsoluteOverflowX | typeof ReaderHeader | typeof ReaderBody | typeof AckSections | typeof AckSectionTemplates | typeof AckOptions | typeof AckFixedElement | typeof AckModal | typeof AckModalLayout | typeof AckArray | typeof AckFixedElementStage)[];
